version: '3.8'

services:
  wolflite:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - DB_KEY=${DB_KEY}
    volumes:
      - ./data:/app/instance
      - ./uploads:/app/static/uploads
    restart: unless-stopped

  cloudFlared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run flasktunnel
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}